image: cookielab/nodejs:8

publish:
  tags:
    - docker
  before_script:
    - echo "$NPMRC" > ~/.npmrc
  script:
    - npm version "$CI_COMMIT_TAG" --no-git-tag-version --allow-same-version
    - npm publish --verbose
  only:
    - tags

github:
  tags:
    - docker
  dependencies: []
  image: cookielab/git-mirror:2.15
  before_script:
    - eval $(ssh-agent -s)
    - import-ssh-key
    - git config --global user.email "robot@cookielab.io"
    - git config --global user.name "Cookie Monster"
  script:
    - git remote rm mirror || true
    - git remote add mirror git@github.com:cookielab/eslint-plugin-custom-rules.git
    - git checkout -B master origin/master
    - git push mirror master
    - git push mirror master --tags
  only:
    - tags
